/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Games
 * Id: 97af34f0-6dd1-4091-ba36-71a16134d12d
 * Codename: games
 */
export type Games =
  | 'magic_the_gathering'
  | 'pokemon'
  | 'warhammer_40k'
  | 'yu_gi_oh';
