/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Post Type
 * Id: d4d7007f-a4bb-4ac2-8ecd-79246ffc2443
 * Codename: post_type
 */
export type PostType = 'article' | 'blog' | 'review' | 'news_item';
