/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Dev 12/16
 * Project Id: 50e65054-5048-00e7-8921-8015e3a9f73d
 */
export const assetFolders = {
  /**
   * new folder
   */
  newFolder: {
    id: '59db2293-16a9-4476-aecc-e4ea38b222f0',
    name: 'new folder',
    externalId: undefined,
    folders: {},
  },
} as const;
