/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Dev 12/16
 * Project Id: 50e65054-5048-00e7-8921-8015e3a9f73d
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
