/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Dev 12/16
 * Project Id: 50e65054-5048-00e7-8921-8015e3a9f73d
 */
export const languages = {
  /**
   * Chinese
   */
  zh: {
    codename: 'zh',
    id: '0f76fd28-24e4-4d18-ad8f-16767c1e3918',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Chinese',
  },

  /**
   * English
   */
  en: {
    codename: 'en',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English',
  },

  /**
   * French
   */
  fr: {
    codename: 'fr',
    id: '99f062d5-3f7b-4bb1-9215-cea244f704e6',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'French',
  },

  /**
   * German
   */
  de: {
    codename: 'de',
    id: 'bff65a26-2a59-4d99-8151-92284efd5c6f',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'German',
  },

  /**
   * spanish
   */
  es: {
    codename: 'es',
    id: '7a43f993-44f8-4b5b-b21b-90f2ee6b25e6',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'spanish',
  },
} as const;
