/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Dev 12/16
 * Project Id: 50e65054-5048-00e7-8921-8015e3a9f73d
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: 'd6c675f7-0c30-4ccb-8a30-8bd220626c2b',
    name: 'Project manager',
  },

  /**
   * Untitled role
   */
  untitledRole: {
    codename: undefined,
    id: 'e2d444cb-3755-4493-bc38-c8a81f49575d',
    name: 'Untitled role',
  },
} as const;
