/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Dev 12/16
 * Project Id: 50e65054-5048-00e7-8921-8015e3a9f73d
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
