/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: new Dev 12/13
 * Project Id: 1b7c0dae-510f-0024-f8b6-309cd1c643af
 */
export const assetFolders = {
  /**
   * new folder
   */
  newFolder: {
    id: '59db2293-16a9-4476-aecc-e4ea38b222f0',
    name: 'new folder',
    externalId: undefined,
    folders: {},
  },
} as const;
