/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: new Dev 12/13
 * Project Id: 1b7c0dae-510f-0024-f8b6-309cd1c643af
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
