/**
 * Generated by '@kontent-ai/model-generator@5.6.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Production
 * Project Id: 76514a5c-03db-0056-e61d-13253a67364b
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },

  /**
   * spanish
   */
  es: {
    codename: 'es',
    id: '7a43f993-44f8-4b5b-b21b-90f2ee6b25e6',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'spanish',
  },
};
