/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: new Dev 12/13
 * Project Id: 1b7c0dae-510f-0024-f8b6-309cd1c643af
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '454ed705-058f-4600-a764-928abdf4e130',
    name: 'Project manager',
  },

  /**
   * Untitled role
   */
  untitledRole: {
    codename: undefined,
    id: '7e83f19a-37f1-4add-a13c-bf4144433bba',
    name: 'Untitled role',
  },
} as const;
