/**
 * Generated by '@kontent-ai/model-generator@5.6.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Production
 * Project Id: 76514a5c-03db-0056-e61d-13253a67364b
 */
export const roles = {
  /**
   * Untitled role
   */
  untitledRole: {
    codename: undefined,
    id: 'f1bb327b-7757-433b-8062-2ff322d19340',
    name: 'Untitled role',
  },

  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '492839ea-fe8f-4c27-a0fb-423106251725',
    name: 'Project manager',
  },
};
