/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: new Dev 12/13
 * Project Id: 1b7c0dae-510f-0024-f8b6-309cd1c643af
 */
export const taxonomies = {
  /**
   * Games
   */
  games: {
    codename: 'games',
    id: '97af34f0-6dd1-4091-ba36-71a16134d12d',
    externalId: undefined,
    name: 'Games',
    terms: {
      magic_the_gathering: {
        codename: 'magic_the_gathering',
        id: 'cb59cfb3-c9ab-4f2d-8558-7c75d7985eb2',
        externalId: undefined,
        name: 'Magic The Gathering',
        terms: {},
      },
      pokemon: {
        codename: 'pokemon',
        id: '4b6273a0-3fd4-4b0a-b87c-8241102a2bb9',
        externalId: undefined,
        name: 'Pokemon',
        terms: {},
      },
      warhammer_40k: {
        codename: 'warhammer_40k',
        id: 'b6970e3d-31ac-4451-8f8f-681387300b18',
        externalId: undefined,
        name: 'Warhammer 40k',
        terms: {},
      },
      yu_gi_oh: {
        codename: 'yu_gi_oh',
        id: 'b6303c00-be12-4163-ac02-dcdf7c6b66eb',
        externalId: undefined,
        name: 'Yu-Gi-Oh',
        terms: {},
      },
    },
  },

  /**
   * Post Type
   */
  post_type: {
    codename: 'post_type',
    id: 'd4d7007f-a4bb-4ac2-8ecd-79246ffc2443',
    externalId: undefined,
    name: 'Post Type',
    terms: {
      article: {
        codename: 'article',
        id: '8c4e6ce1-dffc-4f45-8249-c59e000065af',
        externalId: undefined,
        name: 'Article',
        terms: {},
      },
      blog: {
        codename: 'blog',
        id: 'a25b4e45-2e15-4026-a999-1e9ebf83c3a4',
        externalId: undefined,
        name: 'Blog',
        terms: {},
      },
      news_item: {
        codename: 'news_item',
        id: '6de074b6-3bfa-4c5b-8d58-701967d28f51',
        externalId: undefined,
        name: 'News Item',
        terms: {},
      },
      review: {
        codename: 'review',
        id: '2393c6e3-efd5-4d30-aba0-f908cb110aa2',
        externalId: undefined,
        name: 'Review',
        terms: {},
      },
    },
  },
} as const;
