/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: new Dev 12/13
 * Project Id: 1b7c0dae-510f-0024-f8b6-309cd1c643af
 */
export const webhooks = {
  /**
   * Algolia
   * Last modified: Mon Oct 17 2022 13:26:57 GMT-0500 (Central Daylight Time)
   */
  algolia: {
    url: 'https://zesty-vacherin-af743b.netlify.app/.netlify/functions/algolia-update-webhook&index=sandbox-index&slug=url-slug',
    id: '78b87d8c-552a-42ba-ab10-f649ef4e77b2',
    name: 'Algolia',
  },

  /**
   * Translation
   * Last modified: Mon Nov 21 2022 08:34:28 GMT-0600 (Central Standard Time)
   */
  translation: {
    url: 'https://3f9b-68-76-149-57.eu.ngrok.io/webhook',
    id: 'fb9dc834-4e6a-4a50-b821-c8cb2f4added',
    name: 'Translation',
  },
} as const;
