/**
 * Generated by '@kontent-ai/model-generator@5.6.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Production
 * Project Id: 76514a5c-03db-0056-e61d-13253a67364b
 */
export const webhooks = {};
