/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Support Sandbox 🤠
 * Environment: Production
 * Project Id: 76514a5c-03db-0056-e61d-13253a67364b
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
