import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Algolia
 * Id: 80a0595d-3312-445b-a033-3a8bcd7704a7
 * Codename: algolia
 */
export type Algolia = IContentItem<{
  /**
   * Algolia (custom)
   * Required: false
   * Id: dd65142b-7a91-40d7-b403-a1384c837522
   * Codename: algolia
   */
  algolia: Elements.CustomElement;
}>;
