import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Asset
 * Id: 94ad6916-cc57-4b2f-a28d-243f6d8c18d8
 * Codename: asset
 */
export type Asset = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: d503e96c-889a-4d04-8bf1-4961e141aeea
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Asset (asset)
   * Required: false
   * Id: 4b84b981-0282-4792-8509-c1ce4878d379
   * Codename: asset
   */
  asset: Elements.AssetsElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 996ba739-5427-41f1-82d0-4feb6a87244f
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Untitled linked items (modular_content)
   * Required: false
   * Id: 18478604-cfe2-4534-b4fe-67fc93b5a1ac
   * Codename: untitled_linked_items
   */
  untitled_linked_items: Elements.LinkedItemsElement<IContentItem>;
}>;
