import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Post } from './post';
import { Games } from '../taxonomies/games';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Author
 * Id: f5573bef-ec0b-499c-9a4e-1ac2605c2689
 * Codename: author
 */
export type Author = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: 33ade4c4-905c-4fbb-8084-3009604ebbe9
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Bio (rich_text)
   * Required: false
   * Id: 159955b1-dcca-4a1c-ae4b-329c7063a8da
   * Codename: bio
   */
  bio: Elements.RichTextElement;

  /**
   * Posts (modular_content)
   * Required: false
   * Id: 87d1770d-23cb-4269-ad7c-a03212654e4e
   * Codename: posts
   */
  posts: Elements.LinkedItemsElement<Post>;

  /**
   * Games (taxonomy)
   * Required: false
   * Id: f1638e51-c2dd-4993-9df8-0b527a745597
   * Codename: games
   */
  games: Elements.TaxonomyElement<Games>;
}>;
