import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Cloudinary
 * Id: cf604944-231a-411a-83de-a208f83cbebc
 * Codename: cloudinary
 */
export type Cloudinary = IContentItem<{
  /**
   * Cloudinary Manager (custom)
   * Required: false
   * Id: 372e6b4a-1d54-4182-b2f6-db2099c73f02
   * Codename: cloudinary_manager
   */
  cloudinary_manager: Elements.CustomElement;
}>;
