import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Author } from './author';
import { Games } from '../taxonomies/games';
import { PostType } from '../taxonomies/post_type';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Post
 * Id: 94ae1c1e-778d-416c-b476-a6adfa1d3442
 * Codename: post
 */
export type Post = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: dc9534f1-edd9-4974-8b82-2f409d8126e2
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Author (modular_content)
   * Required: false
   * Id: 5dc7d4e9-2c0f-4341-9e1c-3265f6850d35
   * Codename: author
   */
  author: Elements.LinkedItemsElement<Author>;

  /**
   * Image (asset)
   * Required: false
   * Id: 04b9a500-ec7f-45e9-8f61-bbe51b18467b
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Games (taxonomy)
   * Required: false
   * Id: 6c621277-e19b-4620-bdb1-3c70bf1bd3a6
   * Codename: games
   */
  games: Elements.TaxonomyElement<Games>;

  /**
   * Post Type (taxonomy)
   * Required: false
   * Id: 94b56b2b-4a86-4b97-beec-01ee588cfa3a
   * Codename: post_type
   */
  post_type: Elements.TaxonomyElement<PostType>;
}>;
