import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product
 * Id: 1a89fcd7-b2f9-4f2a-97fd-f32017facc1f
 * Codename: product
 */
export type Product = IContentItem<{
  /**
   * Shopify (custom)
   * Required: false
   * Id: 90ed52ef-1577-47e4-9195-7be8e2211c26
   * Codename: shopify
   */
  shopify: Elements.CustomElement;

  /**
   * Name (text)
   * Required: false
   * Id: 8ea0ba90-067d-448a-a9c7-4b45858915f1
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 13c4c0be-032e-457c-872f-7b97d4e87ac7
   * Codename: description
   */
  description: Elements.RichTextElement;


  
}>;
