import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Rich Text
 * Id: 03b3ea73-ac31-4d4a-9878-b02d4123b7bc
 * Codename: rich_text
 */
export type RichText = IContentItem<{
  /**
   * Rich Text (rich_text)
   * Required: false
   * Id: 3cda6d1f-5798-4e73-bee8-ea48c745d008
   * Codename: rich_text
   */
  rich_text: Elements.RichTextElement;
}>;
