import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Games } from '../taxonomies/games';
import { Product } from './product';

/**
 * Generated by '@kontent-ai/model-generator@5.6.0'
 *
 * Seller
 * Id: cc27df69-7bc9-4c7d-9a25-51a35996447b
 * Codename: seller
 */
export type Seller = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: 9cc64ebc-3976-4206-89e0-edafe98962e5
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Games (taxonomy)
   * Required: true
   * Id: 865c74b0-05c8-4e98-9cfb-30f388071034
   * Codename: games
   */
  games: Elements.TaxonomyElement<Games>;

  /**
   * Bio (rich_text)
   * Required: false
   * Id: 3310e2f5-68db-42ee-b684-c2378bd3f256
   * Codename: bio
   */
  bio: Elements.RichTextElement;

  /**
   * Product List (modular_content)
   * Required: true
   * Id: e71f909c-6035-4017-958f-24a655f68d39
   * Codename: products
   */
  products: Elements.LinkedItemsElement<Product>;
}>;
