import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.6.0'
 *
 * Shopify
 * Id: e8d7e0ff-cf51-4ed4-95cc-d466804ccc74
 * Codename: shopify
 */
export type Shopify = IContentItem<{
  /**
   * Shopify (custom)
   * Required: false
   * Id: d2c99313-95db-4283-b767-d3a020415ad7
   * Codename: shopify
   */
  shopify: Elements.CustomElement;
}>;
