import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Asset } from './asset';
import { type Games } from '../taxonomies/games';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Trading Card
 * Id: 6620eaed-a977-4a80-9c7e-862f33df3653
 * Codename: trading_card
 */
export type TradingCard = IContentItem<{
  /**
   * Condition (multiple_choice)
   * Required: false
   * Id: 3b4aee17-5b44-40cd-9a74-4dd93565dfd6
   * Codename: condition
   */
  condition: Elements.MultipleChoiceElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 60e92346-fc77-48c4-bfc1-cb6959813d32
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Games (taxonomy)
   * Required: false
   * Id: 62724f0a-66b2-460f-a645-993bbab30a25
   * Codename: game
   */
  game: Elements.TaxonomyElement<Games>;

  /**
   * Image (modular_content)
   * Required: false
   * Id: 3f7d7cb5-1598-47d6-9714-80a232e028fa
   * Codename: image
   */
  image: Elements.LinkedItemsElement<Asset>;

  /**
   * Price (number)
   * Required: false
   * Id: 6c9ba18d-434a-4593-8d37-0b4e18bf8cf4
   * Codename: price
   */
  price: Elements.NumberElement;

  /**
   * Seller (modular_content)
   * Required: false
   * Id: 7a934617-f198-47c2-b097-816bdb11f1be
   * Codename: seller
   */
  seller: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Shopify (custom)
   * Required: false
   * Id: bf14cddc-bd49-45cd-8127-0ed4537c25e6
   * Codename: shopify
   */
  shopify: Elements.CustomElement;

  /**
   * Title (text)
   * Required: false
   * Id: c4bc6c59-6574-4896-b214-aa8818b60ba8
   * Codename: title
   */
  title: Elements.TextElement;
}>;
